### ISSUE TITLE
Add column for transit mid-point time

### ISSUE THREAD

**Issue by brackham** [PandoraMission/PandoraTargetList#1]
To help mask transits in TESS light curves, it would be nice to also include the transit mid-point time from NASA Exoplanet Archive (`pl_tranmid`) in the spreadsheet.

**Comment by brackham** [comment]
In fact, it could be nice to just include every column from the table in the NASA Exoplanet Archive.

**Comment by benhord** [comment]
This is a good call. I've just pushed a version of the long list with every column from the NASA Exoplanet Archive included.
