### ISSUE TITLE
Default NIRDA settings should be fowler_4

### ISSUE THREAD

**Issue by mrtommyb** [PandoraMission/PandoraTargetList#3]
Currently the default NIRDA sampling scheme seems to be fowler_1, it should be fowler_4.

**Comment by benhord** [comment]
This problem stemmed from a bug where the each NIRDA readout was erroneously being integrated for the full integration time rather than the readout time, resulting in almost every single target being too bright for fowler_4. The current version of the code now reflects the correct readout time.
