### ISSUE TITLE
Develop new method for listing targets within a category and the prioritization

### ISSUE THREAD

**Issue by mrtommyb** [PandoraMission/PandoraTargetList#5]
I would like there to be a separate priority file for each category. The category names are:
primary-exoplanet/
secondary-exoplanet/
auxiliary-exoplanet/
auxiliary-standard/
monitoring-standard/
time-critical/
occultation-standard/

and these files should list every single target in the category.

**Comment by benhord** [comment]
This is now implemented with the merge of pull request #15 so I'm closing the issue.
